on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
    sample_job:
      runs-on: ubuntu-latest
      name: Pytest passing tests
      steps:
        - uses: actions/setup-python@v2
          with:
            python-version: '3.12'
        - name: Checkout
          uses: actions/checkout@v2
        - name: Pytest Action Step
          id: pytest
          uses: paolorechia/fast-pytest-github-action@develop
          with:
            pytest_args: 'test_output.py'
            requirements_file: 'test_requirements.txt'
